// Isolated synthetic evidence only; never touches the real ledger.
import { chromium, expect } from '@playwright/test';
import { spawn } from 'node:child_process';
import { mkdtemp, rm, mkdir, writeFile, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer, request as httpRequest } from 'node:http';

const root = dirname(fileURLToPath(import.meta.url));
const dir = await mkdtemp(join(tmpdir(), 'observatory-browser-'));
const proc = spawn('python3', [join(root,'server.py'), '--no-scan', '--db', join(dir,'test.sqlite3'), '--port','0']);
let browser, forwarder;
try {
  const upstream = await new Promise((resolve,reject)=>{
    const timer=setTimeout(()=>reject(new Error('Test server startup timed out')),10000);
    proc.on('error',reject);proc.stderr.on('data',d=>process.stderr.write(d));
    proc.stdout.on('data',data=>{const match=data.toString().match(/http:\/\/127\.0\.0\.1:\d+/);if(match){clearTimeout(timer);resolve(match[0]);}});
  });
  // Reproduce desktop forwarding: retain the browser's Host and Origin while
  // sending requests to a different backend port. Exercise reads and writes.
  forwarder = createServer((req,res)=>{
    const forwarded = httpRequest(upstream,{path:req.url,method:req.method,headers:req.headers},response=>{
      res.writeHead(response.statusCode,response.headers);response.pipe(res);
    });
    forwarded.on('error',()=>{res.writeHead(502);res.end('Test forwarder failed');});
    req.pipe(forwarded);
  });
  await new Promise((resolve,reject)=>{forwarder.once('error',reject);forwarder.listen(0,'127.0.0.1',resolve);});
  const base = 'http://localhost:'+forwarder.address().port;
  browser = await chromium.launch({...(process.env.OBSERVATORY_BROWSER?{executablePath:process.env.OBSERVATORY_BROWSER}:{}),headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
  await page.goto(base);
  await expect(page.getByRole('heading',{name:'Usage ledger',exact:true})).toBeVisible();
  await expect(page.getByRole('heading',{name:'No records match'})).toBeVisible();
  const timestamp=new Date().toISOString();
  const record=(type,payload)=>JSON.stringify({type,timestamp,payload})+'\n';
  const tokens={input_tokens:100,cached_input_tokens:50,output_tokens:20,reasoning_output_tokens:10,total_tokens:120};
  let content=record('session_meta',{id:'fixture-task',cwd:'/fixture/project',originator:'codex_cli',model_provider:'openai'});
  content+=record('turn_context',{model:'fixture-model',turn_id:'fixture-turn'});
  content+=record('event_msg',{type:'token_count',info:null,rate_limits:{plan_type:'pro',limit_id:'codex',primary:{used_percent:49,window_minutes:10080,resets_at:Math.floor(Date.now()/1000)+604800},secondary:null}});
  for(let i=0;i<55;i++) content+=record('token_usage_record',{response_id:'fixture-response-'+i,thread_id:'fixture-task',usage:tokens});
  const importFile=async(name,text,scope='')=>{
    await page.locator('#open-import').click();
    await page.locator('#import-form [name="scope"]').fill(scope);
    await page.locator('[name="file"]').setInputFiles({name,mimeType:'application/json',buffer:Buffer.from(text)});
    await page.getByRole('button',{name:'Import evidence',exact:true}).click();
    await expect(page.locator('#import-dialog')).not.toBeVisible();
  };
  await importFile('synthetic.jsonl',content);
  await expect(page.locator('.stats')).toContainText('6,600 exact');
  await expect(page.locator('.ledger-table tbody tr')).toHaveCount(50);
  await page.getByRole('button',{name:'Next records'}).click();
  await expect(page.locator('.ledger-table tbody tr')).toHaveCount(5);
  await page.getByRole('button',{name:'Previous records'}).click();
  await page.locator('[data-event]').first().click();
  await expect(page.locator('#detail')).toBeVisible();
  await page.getByText('Declare owner, project and purpose',{exact:true}).click();
  await page.locator('[name="apply_scope"]').selectOption('task');
  await page.locator('#attribute-form [name="project"]').fill('Release');
  await page.locator('[name="principal"]').fill('Alice');
  await page.locator('[name="purpose"]').fill('Ship release <img src=x onerror=alert(1)>');
  await page.locator('#attribute-form [name="reason"]').fill('Map to fixture ticket 42');
  await page.getByRole('button',{name:'Save attribution',exact:true}).click();
  await expect(page.locator('#toast')).toContainText('55 records');
  await expect(page.locator('#detail-content')).toContainText('Alice (declared attribution)');
  await expect(page.locator('#detail-content img')).toHaveCount(0);
  const [evidence] = await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download evidence JSON'}).click()]);
  expect(evidence.suggestedFilename()).toMatch(/^evidence-/);
  await page.getByRole('button',{name:'Close record'}).click();
  await page.locator('#search').fill('Alice');
  await expect(page.locator('.stats')).toContainText('6,600 exact');
  await page.locator('#search').fill('nonexistent-query');
  await expect(page.getByRole('heading',{name:'No records match'})).toBeVisible();
  await page.locator('#search').fill('');
  await page.locator('[data-nav="projects"]').click();
  await page.locator('.budget-form [name="tokens"]').fill('5000');
  await page.getByRole('button',{name:'Save budget'}).click();
  await expect(page.locator('#toast')).toContainText('Token budget saved');
  await page.locator('[data-nav="alerts"]').click();
  await expect(page.getByRole('heading',{name:'Project token budget reached'})).toBeVisible();
  await page.getByRole('button',{name:'Acknowledge',exact:true}).click();
  await expect(page.locator('.alert-row')).toContainText('acknowledged');
  await page.locator('[data-nav="activity"]').click();
  await expect(page.locator('#main')).toContainText('Local audit chain verified');
  await expect(page.locator('#main')).toContainText('58 entries');
  // 55 per-record changes + import + budget + acknowledgement = 58.
  const chain=await (await page.request.get(base+'/api/state')).json();
  expect(chain.integrity.entries).toBe(58);
  const bucket={data:[{start_time:1788825600,end_time:1788912000,results:[{object:'organization.usage.completions.result',project_id:'fixture-provider-project',input_tokens:100,input_cached_tokens:50,output_tokens:20,num_model_requests:1}]}],has_more:false};
  await importFile('usage.json',JSON.stringify(bucket),'Fixture API');
  await page.locator('[data-nav="provider"]').click();
  await expect(page.locator('#main')).toContainText('fixture-provider-project');
  await importFile('usage-copy.json',JSON.stringify(bucket),'Fixture API');
  await expect(page.locator('#main')).toContainText('1 of 1 buckets');
  await page.locator('[data-nav="analysis"]').click();
  await page.locator('#by').selectOption('person');
  await expect(page.locator('#main')).toContainText('Alice');
  await expect(page.getByRole('heading',{name:'6,600 observed tokens in this selection'})).toBeVisible();
  await page.locator('#range').selectOption('custom');
  await page.locator('#from').fill(timestamp.slice(0,10));
  await page.locator('#to').fill(timestamp.slice(0,10));
  await page.locator('#granularity').selectOption('response');
  await expect(page.getByRole('heading',{name:'6,600 observed tokens in this selection'})).toBeVisible();
  await importFile('activity.json',JSON.stringify({schema:'observatory.activity.v1',events:[{id:'unfamiliar-device',timestamp,action:'session.used',device:'unknown-device',ip_address:'198.51.100.1'}]}),'Fixture API');
  await page.locator('[data-nav="alerts"]').click();
  await page.getByText('Declare approved devices and networks for imported activity',{exact:true}).click();
  await page.locator('#policy-form [name="scope"]').fill('Fixture API');
  await page.locator('#policy-form [name="devices"]').fill('my-laptop');
  await page.locator('#policy-form [name="networks"]').fill('192.0.2.0/24');
  await page.locator('#policy-form [name="reason"]').fill('Fixture inventory');
  await page.getByRole('button',{name:'Save access policy'}).click();
  await expect(page.getByRole('heading',{name:'Activity outside declared access policy'})).toBeVisible();
  await page.getByRole('button',{name:'Inspect activity evidence'}).click();
  await expect(page.locator('#detail')).toContainText('unknown-device');
  await page.getByRole('button',{name:'Close record'}).click();
  await page.locator('[data-nav="ledger"]').click();
  await expect(page.locator('.stats')).toContainText('6,600 exact');
  const [csv] = await Promise.all([page.waitForEvent('download'),page.getByRole('link',{name:'Export CSV'}).click()]);
  expect(csv.suggestedFilename()).toBe('observatory-ledger.csv');
  await mkdir(join(root,'test-results'),{recursive:true});
  await page.screenshot({path:join(root,'test-results','ledger-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await expect(page.locator('[data-event]').first()).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:join(root,'test-results','ledger-mobile.png'),fullPage:true});
  await page.locator('[data-event]').first().click();
  await expect(page.getByRole('button',{name:'Close record'})).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.locator('#detail')).not.toBeVisible();
  await page.locator('[data-nav="coverage"]').click();
  await page.getByRole('button',{name:'Add source folder'}).click();
  await page.locator('#source-form [name="label"]').fill('Windows ChatGPT / Work');
  await page.locator('#source-form [name="path"]').fill(String.raw`C:\Users\alex\.codex`);
  await page.getByRole('button',{name:'Save source',exact:true}).click();
  await expect(page.locator('#source-dialog')).not.toBeVisible();
  let sourceRow=page.locator('.source-row').filter({hasText:'Windows ChatGPT / Work'});
  await expect(sourceRow).toContainText('unavailable');
  await page.reload();
  await expect(sourceRow).toContainText('Windows ChatGPT / Work');
  const sourceDir=join(dir,'windows-copy');await mkdir(join(sourceDir,'sessions'),{recursive:true});
  // A copy of the already imported response records must not increase totals.
  await writeFile(join(sourceDir,'sessions','copied.jsonl'),content);
  await sourceRow.getByRole('button',{name:'Edit',exact:true}).click();
  await page.locator('#source-form [name="access_path"]').fill(sourceDir);
  await page.getByRole('button',{name:'Save source',exact:true}).click();
  await expect(page.locator('#source-dialog')).not.toBeVisible();
  await expect.poll(async()=>{const response=await page.request.get(base+'/api/state');return (await response.json()).sources[0].status;}).toBe('ready');
  await page.reload();await expect(sourceRow).toContainText('ready');
  await sourceRow.getByRole('button',{name:'Disable',exact:true}).click();
  await expect(sourceRow).toContainText('disabled');
  await sourceRow.getByRole('button',{name:'Enable',exact:true}).click();
  await expect(sourceRow.getByRole('button',{name:'Disable',exact:true})).toBeVisible();
  await page.screenshot({path:join(root,'test-results','sources-mobile.png'),fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await sourceRow.getByRole('button',{name:'Remove',exact:true}).click();
  await expect(page.locator('.source-row')).toHaveCount(0);
  const included=await (await page.request.get(base+'/api/ledger')).json();expect(included.summary.total_tokens).toBe(6600);
  const [full] = await Promise.all([page.waitForEvent('download'),page.getByRole('link',{name:'Export complete evidence'}).click()]);
  expect(full.suggestedFilename()).toBe('observatory-evidence.json');
  // Every ledger column sorts the full dataset, including beyond page one.
  await page.setViewportSize({width:1440,height:1000});
  let varying=record('session_meta',{id:'sort-task',cwd:'/sort/project'});
  varying+=record('turn_context',{model:'AAA'});
  varying+=record('token_usage_record',{response_id:'sort-small',thread_id:'sort-task',usage:{input_tokens:2,output_tokens:20}});
  varying+=record('turn_context',{model:'ZZZ'});
  varying+=record('token_usage_record',{response_id:'sort-large',thread_id:'sort-task',usage:{input_tokens:1000,output_tokens:20}});
  await importFile('sorting.jsonl',varying);
  await page.locator('[data-nav="ledger"]').click();
  await page.locator('#sort-ledger-total_tokens').click();
  await expect(page.locator('.ledger-table tbody tr').first().locator('td').last()).toHaveText('22');
  await expect(page.locator('#sort-ledger-total_tokens').locator('..')).toHaveAttribute('aria-sort','ascending');
  await page.locator('#sort-ledger-total_tokens').press('Enter');
  await expect(page.locator('.ledger-table tbody tr').first().locator('td').last()).toHaveText('1,020');
  await expect(page.locator('#sort-ledger-total_tokens')).toBeFocused();
  await page.getByRole('button',{name:'Next records',exact:true}).click();
  await expect(page.locator('.ledger-table tbody tr')).toHaveCount(7);
  await page.locator('#sort-ledger-model').click();
  await expect(page.locator('.ledger-table tbody tr').first()).toContainText('AAA');
  await expect(page.locator('.ledger-table tbody tr')).toHaveCount(50);
  await page.locator('[data-nav="analysis"]').click();
  await page.locator('#sort-analysis-records').click();
  await expect(page.locator('#sort-analysis-records').locator('..')).toHaveAttribute('aria-sort','ascending');
  await page.locator('[data-nav="provider"]').click();
  await page.locator('#sort-provider-values').click();
  await expect(page.locator('#sort-provider-values').locator('..')).toHaveAttribute('aria-sort','ascending');
  await page.locator('[data-nav="activity"]').click();
  await page.locator('#sort-activity-actor').click();
  await expect(page.locator('#sort-activity-actor').locator('..')).toHaveAttribute('aria-sort','ascending');
  await page.locator('[data-nav="coverage"]').click();
  await page.locator('#sort-coverage-surface').click();
  await expect(page.locator('#main table tbody tr').first()).toContainText('API organization');
  await page.locator('[data-nav="limits"]').click();
  await expect(page.getByRole('heading',{name:'Limits & cycles',exact:true})).toBeVisible();
  await expect(page.locator('.limit-cards').first()).toContainText('49% used');
  await expect(page.locator('.limit-cards').first()).toContainText('51% remaining at observation');
  await expect(page.locator('.limit-cards').first()).toContainText('Weekly · 7 days');
  await expect(page.locator('.limit-cards').first()).toContainText('Not reported');
  await page.locator('#sort-limits-primary').click();
  await expect(page.locator('#sort-limits-primary').locator('..')).toHaveAttribute('aria-sort','ascending');
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:join(root,'test-results','limits-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:join(root,'test-results','limits-mobile.png'),fullPage:true});
  await page.locator('[data-nav="ledger"]').click();
  await page.locator('#search').fill('fixture-response');
  await expect(page.locator('.ledger-table tbody tr').first()).toContainText('fixture-model');
  await expect(page.locator('.ledger-table tbody tr')).toHaveCount(50);
  await page.locator('[data-event]').first().click();
  await expect(page.locator('#detail')).toContainText('Quota position near this record');
  await expect(page.locator('#detail')).toContainText('49% used');
  await page.getByRole('button',{name:'View this source’s limit history'}).first().click();
  await expect(page.getByRole('button',{name:'Clear limit source filter'})).toBeVisible();
  await expect(page.locator('.limits-table tbody tr')).toHaveCount(1);
  // An expired five-hour window and an independently reported weekly zero
  // must render as stale evidence and a real zero, respectively.
  const expired=JSON.stringify({type:'event_msg',timestamp:'2026-01-01T01:00:00Z',payload:{type:'token_count',info:null,rate_limits:{plan_type:'pro',limit_id:'codex',primary:{used_percent:49.5,window_minutes:300,resets_at:1767247200},secondary:{used_percent:0,window_minutes:10080,resets_at:1767801600}}}})+'\n';
  await importFile('expired-limits.jsonl',expired);
  await page.getByRole('button',{name:'Clear limit source filter'}).click();
  await page.locator('#limit-search').fill('expired-limits.jsonl');
  await expect(page.locator('.limit-cards').first()).toContainText('49.5% used');
  await expect(page.locator('.limit-cards').first()).toContainText('50.5% remaining at observation');
  await expect(page.locator('.limit-cards').first()).toContainText('5 hours');
  await expect(page.locator('.limit-cards').first()).toContainText('0% used');
  await expect(page.locator('.limit-cards').first()).toContainText('Reset time has passed; remaining now unknown.');
  // Drill-through analytics over multiple projects, models and tasks.
  await page.setViewportSize({width:1440,height:1000});
  let analyticsFixture='';
  for(let project=0;project<8;project++)for(let model=0;model<2;model++){
    const id=`analytics-${project}-${model}`;
    analyticsFixture+=record('session_meta',{id,cwd:'/analytics/Project-'+project});
    analyticsFixture+=record('turn_context',{model:'analysis-model-'+model});
    analyticsFixture+=record('token_usage_record',{response_id:id,usage:{input_tokens:(project+1)*1000,cached_input_tokens:(project+1)*500,output_tokens:20}});
  }
  await importFile('analytics.jsonl',analyticsFixture);
  await page.locator('[data-nav="analysis"]').click();
  await page.locator('#search').fill('/analytics/');
  await page.locator('#by').selectOption('project');
  await expect(page.getByRole('heading',{name:'72,320 observed tokens in this selection',exact:true})).toBeVisible();
  await expect(page.locator('.donut')).toHaveCount(2);
  await expect(page.locator('.analytics-trend')).toBeVisible();
  await expect(page.locator('.heatmap-wrap svg')).toBeVisible();
  await expect(page.locator('.chart-legend').first()).toContainText('All other groups');
  await expect(page.locator('#trend-split')).toHaveValue('model');
  await expect(page.locator('.model-trend-legend button')).toHaveCount(2);
  await expect(page.locator('.analytics-trend [data-trend-model]')).toHaveCount(2);
  await page.getByRole('button',{name:/^Focus on analysis-model-0:/}).press('Enter');
  await expect(page.locator('.analysis-chips')).toContainText('Model:');
  await expect(page.getByRole('button',{name:'Remove period focus'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'36,160 observed tokens in this selection',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Back one level'}).click();
  await expect(page.getByRole('heading',{name:'72,320 observed tokens in this selection',exact:true})).toBeVisible();
  await page.locator('.model-trend-legend [data-ana-value="analysis-model-1"]').click();
  await expect(page.getByRole('heading',{name:'36,160 observed tokens in this selection',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Remove period focus'})).toHaveCount(0);
  await page.getByRole('button',{name:'Back one level'}).click();
  await page.locator('#trend-split').selectOption('tokens');
  await expect(page.locator('.analytics-trend [data-trend-model]')).toHaveCount(0);
  await expect(page.locator('.trend-legend')).toContainText('Cached input');
  await page.locator('#trend-split').selectOption('model');
  await expect(page.locator('.model-trend-legend button')).toHaveCount(2);
  await page.evaluate(()=>{document.activeElement.blur();window.scrollTo(0,0)});
  await page.screenshot({path:join(root,'test-results','analytics-desktop.png'),fullPage:true});
  await page.locator('.legend-item[data-ana-value="/analytics/Project-7"]').click();
  await expect(page.locator('#by')).toHaveValue('model');
  await expect(page.locator('.analysis-chips')).toContainText('Project:');
  await expect(page.getByRole('heading',{name:'16,040 observed tokens in this selection',exact:true})).toBeVisible();
  await page.locator('.analysis-table [data-ana-value="analysis-model-0"]').click();
  await expect(page.locator('#by')).toHaveValue('task');
  await expect(page.getByRole('heading',{name:'8,020 observed tokens in this selection',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Open matching records →',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Usage ledger',exact:true})).toBeVisible();
  await expect(page.locator('.ledger-table tbody tr')).toHaveCount(1);
  await expect(page.locator('.stats')).toContainText('8,020 exact');
  const csvPath=await page.getByRole('link',{name:'Export CSV',exact:true}).getAttribute('href');
  const filteredCsv=await (await page.request.get(base+csvPath)).text();
  expect(filteredCsv).toContain('analytics-7-0');expect(filteredCsv).not.toContain('analytics-7-1');
  await page.locator('[data-event]').first().click();
  await expect(page.locator('#detail')).toContainText('analytics-7-0');
  await page.getByRole('button',{name:'Close record'}).click();
  await page.locator('[data-nav="analysis"]').click();
  await page.getByRole('button',{name:'Back one level'}).click();
  await expect(page.getByRole('heading',{name:'16,040 observed tokens in this selection',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Clear drill-downs',exact:true}).click();
  await expect(page.getByRole('heading',{name:'72,320 observed tokens in this selection',exact:true})).toBeVisible();
  await page.locator('#analysis-metric').selectOption('cached_input_tokens');
  await expect(page.locator('.analytics-kpis').first()).toContainText('36,000 exact');
  await page.locator('#sort-analysis-share').click();
  await expect(page.locator('#sort-analysis-share').locator('..')).toHaveAttribute('aria-sort','ascending');
  await page.locator('#analysis-metric').selectOption('total_tokens');
  await page.locator('[data-ana-size="1"]').click();
  await expect(page.locator('.analysis-chips')).toContainText('Response size:');
  await expect(page.getByRole('heading',{name:'72,320 observed tokens in this selection',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Remove response size filter'}).click();
  await expect(page.locator('#granularity')).toHaveValue('');
  await page.locator('.analytics-trend [role="button"]').first().press('Enter');
  await expect(page.getByRole('button',{name:'Remove period focus'})).toBeVisible();
  await page.locator('#range').selectOption('30');
  await expect(page.getByRole('button',{name:'Remove period focus'})).toHaveCount(0);
  const activeHour=new Date(timestamp).getUTCHours().toString().padStart(2,'0'),activeDay=new Date(timestamp).getUTCDay().toString();
  await page.locator(`[data-ana-hour="${activeHour}"][data-ana-weekday="${activeDay}"]`).press('Enter');
  await expect(page.locator('.analysis-chips')).toContainText('Hour (UTC):');
  await expect(page.getByRole('heading',{name:'72,320 observed tokens in this selection',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Clear drill-downs',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>{document.activeElement.blur();window.scrollTo(0,0)});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:join(root,'test-results','analytics-mobile.png'),fullPage:true});
  await page.locator('#search').fill('no-analytics-match');
  await expect(page.getByRole('heading',{name:'No consumption in this selection',exact:true})).toBeVisible();
  // Offline API what-ifs: preserve evidence and compare only priced entries.
  await page.setViewportSize({width:1440,height:1000});
  let costFixture='';
  for(const project of ['A','B']){
    costFixture+=record('session_meta',{id:'cost-'+project,cwd:'/cost-fixture/'+project,model_provider:'openai'});
    costFixture+=record('turn_context',{model:'gpt-5.6-sol'});
    costFixture+=record('token_usage_record',{response_id:'cost-'+project,usage:{input_tokens:100000,cached_input_tokens:50000,cache_write_input_tokens:0,output_tokens:10000,reasoning_output_tokens:5000}});
  }
  await importFile('costs.jsonl',costFixture);
  await page.locator('[data-nav="costs"]').click();
  await expect(page.getByRole('heading',{name:'Cost analysis',exact:true})).toBeVisible();
  await page.locator('#search').fill('/cost-fixture/');
  await expect(page.locator('.cost-table tbody tr')).toHaveCount(2);
  await page.locator('#by').selectOption('project');
  await expect(page.locator('[data-cost-total=baseline]')).toContainText('$0.84');
  await expect(page.locator('[data-cost-total=scenario]')).toHaveCount(0);
  await expect(page.locator('.cost-table th')).toHaveCount(5);
  await page.locator('[data-cost-preset="double"]').click();
  await expect(page.locator('[data-cost-total=scenario]')).toContainText('$1.68');
  await expect(page.locator('.cost-difference')).toContainText('Add $0.84 (100%)');
  await page.locator('[data-cost-preset="no-cache"]').click();
  await expect(page.locator('[data-cost-total=scenario]')).toContainText('$1.20');
  await page.locator('[data-cost-preset="terra"]').click();
  await expect(page.locator('[data-cost-total=scenario]')).toContainText('$0.46');
  await expect(page.locator('#cost-form [name="tier"]')).not.toBeVisible();
  await page.locator('.cost-advanced summary').click();
  await page.locator('#cost-form [name="tier"]').selectOption('batch');
  await page.getByRole('button',{name:'Update estimate',exact:true}).click();
  await expect(page.locator('[data-cost-total=scenario]')).toContainText('$0.23');
  await page.locator('.cost-saved summary').click();
  await page.locator('#cost-scenario-name').fill('Terra batch');
  await page.locator('[data-cost-action="save"]').click();
  await page.locator('[data-cost-preset="reset"]').click();
  await expect(page.locator('[data-cost-total=scenario]')).toHaveCount(0);
  await expect(page.locator('.cost-table th')).toHaveCount(5);
  await page.locator('[data-cost-load="0"]').click();
  await expect(page.locator('[data-cost-total=scenario]')).toContainText('$0.23');
  const [scenarioDownload]=await Promise.all([page.waitForEvent('download'),page.locator('[data-cost-action="json"]').click()]);
  const scenarioJSON=JSON.parse(await readFile(await scenarioDownload.path(),'utf8'));
  expect(scenarioJSON.scenario_config.target).toBe('gpt-5.6-terra');
  expect(Number(scenarioJSON.scenario.total)).toBe(.23);
  expect(scenarioJSON.groups).toHaveLength(2);
  expect(scenarioJSON.catalog.source).toBe('https://developers.openai.com/api/docs/pricing');
  const [costDownload]=await Promise.all([page.waitForEvent('download'),page.locator('[data-cost-action="csv"]').click()]);
  const costCSV=await readFile(await costDownload.path(),'utf8');
  expect(costCSV).toContain('"USD","/cost-fixture/A"');
  expect(costCSV).toContain('"0.115');
  await page.locator('#cost-details-toggle').check();
  await expect(page.locator('.cost-table th')).toHaveCount(9);
  // Hold the user's sort response while the periodic refresh fires. The
  // background refresh must not invalidate the pending foreground render.
  let heldCostResponse;
  const holdCostResponse=route=>{heldCostResponse=route;};
  await page.route('**/api/cost-analysis',holdCostResponse);
  await page.locator('#sort-costs-cached').click();
  await expect.poll(()=>Boolean(heldCostResponse)).toBe(true);
  await page.evaluate(()=>load(true));
  await heldCostResponse.continue();
  await page.unroute('**/api/cost-analysis',holdCostResponse);
  await expect(page.locator('#sort-costs-cached').locator('..')).toHaveAttribute('aria-sort','ascending');
  await page.locator('#cost-details-toggle').uncheck();
  await expect(page.locator('.cost-table th')).toHaveCount(5);
  await page.locator('#sort-costs-scenario').click();
  await expect(page.locator('#sort-costs-scenario').locator('..')).toHaveAttribute('aria-sort','ascending');
  await page.evaluate(()=>{document.activeElement.blur();window.scrollTo(0,0)});
  await page.screenshot({path:join(root,'test-results','costs-desktop.png'),fullPage:true});
  await page.locator('.cost-table [data-cost-group="/cost-fixture/A"]').click();
  await expect(page.locator('#by')).toHaveValue('model');
  await expect(page.locator('.analysis-chips')).toContainText('/cost-fixture/A');
  await expect(page.locator('[data-cost-total=scenario]')).toContainText('$0.12');
  await page.getByRole('link',{name:'Inspect matching usage →',exact:true}).click();
  await expect(page.locator('.ledger-table tbody tr')).toHaveCount(1);
  await page.locator('[data-nav="costs"]').click();
  await page.getByRole('button',{name:'Clear drill-downs',exact:true}).click();
  await expect(page.locator('[data-cost-total=scenario]')).toContainText('$0.23');
  await page.locator('#cost-form [name="target"]').selectOption('custom');
  await expect(page.locator('#cost-custom')).toBeVisible();
  await page.locator('#cost-form [name="custom_input"]').fill('1');
  await page.locator('#cost-form [name="custom_output"]').fill('2');
  // Moving focus away must not let the background refresh erase draft assumptions.
  await page.evaluate(async()=>{document.activeElement.blur();await load(true)});
  await expect(page.locator('#cost-form [name="target"]')).toHaveValue('custom');
  await expect(page.locator('#cost-draft-status')).toContainText('Changes not applied');
  await expect(page.locator('[data-cost-total=scenario]')).toContainText('$0.23');
  await page.getByRole('button',{name:'Update estimate',exact:true}).click();
  await expect(page.locator('[data-cost-total=scenario]')).toContainText('$0.14');
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>{document.activeElement.blur();window.scrollTo(0,0)});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:join(root,'test-results','costs-mobile.png'),fullPage:true});
  await page.locator('#search').fill('/analytics/');
  await page.locator('[data-cost-preset="reset"]').click();
  await expect(page.locator('[data-cost-total=baseline]')).toContainText('Not priced');
  await expect(page.locator('.cost-coverage')).toContainText('Partial estimate');
  await page.locator('#search').fill('no-cost-match');
  await expect(page.getByRole('heading',{name:'No usage in this selection',exact:true})).toBeVisible();
  expect(errors).toEqual([]);
  console.log('Browser checks passed: import, deduplication, pagination, task attribution, XSS escaping, search, budgets, alerts, audit, provider separation, downloads, mobile layout, keyboard dismissal, global column sorting, Pro quota history, interactive analytics, model timeline segments and legend filters, exact drill-down/export matching, chart keyboard controls, record context, and offline cost scenarios, cache/model/tier controls, saved assumptions, decimal exports, and cost drill-through.');
} finally {
  if(browser)await browser.close();
  if(forwarder){forwarder.closeAllConnections();await new Promise(resolve=>forwarder.close(resolve));}
  proc.kill('SIGTERM');
  await rm(dir,{recursive:true,force:true});
}
