'use strict';
let trendMode='model';
let analysisMetric='total_tokens', analysisData=null, analysisTrail=[];
const dimensionLabels={project:'Project',model:'Model',task:'Task',person:'Person / workload',purpose:'Declared purpose',application:'Application',device:'Collector device',directory:'Source folder',branch:'Git branch',evidence:'Evidence type',day:'UTC day',weekday:'Weekday (UTC)',hour:'Hour (UTC)'};
const metricLabels={total_tokens:'Total tokens',input_tokens:'Input tokens',cached_input_tokens:'Cached input',uncached_input_tokens:'Uncached input',output_tokens:'Output tokens',reasoning_output_tokens:'Reasoning output',cache_write_input_tokens:'Cache write',records:'Metering records'};
const sizeBins=[['Under 1k',0,1000],['1k–10k',1000,10000],['10k–100k',10000,100000],['100k–1m',100000,1000000],['1m and above',1000000,null]];
const percent=value=>value==null?'—':new Intl.NumberFormat('en-US',{style:'percent',maximumFractionDigits:1}).format(value);
const readableDimension=(by,value)=>by==='weekday'?['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][Number(value)]:by==='hour'?value+':00–'+value+':59':value;
const drillAttrs=(by,value)=>`data-ana-drill="${esc(by)}" data-ana-value="${esc(value)}"`;
function analysisRemember(){analysisTrail.push({filters:structuredClone(filters),metric:analysisMetric});if(analysisTrail.length>20)analysisTrail.shift();}
function facetChips(){
  const entries=Object.entries(filters.facets||{});
  return (entries.length||filters.tokens_min!=null||filters.drillFrom||filters.drillTo)?`<div class="analysis-chips" aria-label="Active drill-down filters">${entries.map(([by,value])=>`<span class="filter-chip">${esc(dimensionLabels[by])}: <span class="chip-value" title="${esc(value)}">${esc(readableDimension(by,value))}</span><button data-ana-remove="${by}" aria-label="Remove ${esc(dimensionLabels[by])} filter">×</button></span>`).join('')}${filters.tokens_min!=null?`<span class="filter-chip">Response size: ${fmt(filters.tokens_min)}–${filters.tokens_max==null?'∞':fmt(filters.tokens_max)+' (exclusive)'}<button data-ana-remove="size" aria-label="Remove response size filter">×</button></span>`:''}${filters.drillFrom||filters.drillTo?`<span class="filter-chip">Period focus: ${esc(when(filters.drillFrom))} → ${esc(when(filters.drillTo))} UTC<button data-ana-remove="period" aria-label="Remove period focus">×</button></span>`:''}<button data-ana-action="clear">Clear drill-downs</button></div>`:'';
}
function recordQuery(data){const p=new URLSearchParams(query('ledger'));p.set('to',data.period.end);p.set('offset','0');return p.toString();}
function donut(items,total,by,metric,label){
  if(!total)return '<p class="chart-empty">No quantity to divide in this selection.</p>';
  let offset=0;
  const arcs=items.map((r,i)=>{const length=r[metric]/total*100,begin=offset;offset+=length;if(!length)return '';
    return `<g ${r.other?'':drillAttrs(by,r.dimension)} ${r.other?'':`role="button" tabindex="0" aria-label="Focus on ${esc(r.dimension)}"`}><title>${esc(r.dimension)}: ${fmt(r[metric])} (${percent(r[metric]/total)})</title><circle class="pie-segment ${r.color||`palette-${i}`}" cx="100" cy="100" r="72" pathLength="100" fill="none" stroke-width="30" stroke-dasharray="${length} ${100-length}" stroke-dashoffset="${-begin}" transform="rotate(-90 100 100)"/></g>`;
  }).join('');
  return `<div class="donut-layout"><svg class="donut" viewBox="0 0 200 200" role="group" aria-label="${esc(label)}">${arcs}<text x="100" y="99" text-anchor="middle" class="donut-total">${compact(total)}</text><text x="100" y="118" text-anchor="middle" class="donut-caption">${metric==='records'?'records':'tokens'}</text></svg><div class="chart-legend">${items.map((r,i)=>`${r.other?'<div class="legend-item">':`<button class="legend-item" ${drillAttrs(by,r.dimension)} title="Focus on ${esc(r.dimension)}">`}<i class="swatch ${r.color||`palette-${i}`}" aria-hidden="true"></i><span class="legend-label">${esc(readableDimension(by,r.dimension))}<small>${fmt(r[metric])} ${metric==='records'?'records':'tokens'}</small></span><strong>${percent(r[metric]/total)}</strong>${r.other?'</div>':'</button>'}`).join('')}</div></div>`;
}
function rankingChart(data){
  const max=Math.max(...data.ranking.map(r=>r[data.metric]),1);
  return `<div class="rank-bars">${data.ranking.map((r,i)=>`<button class="rank-row" ${drillAttrs(data.by,r.dimension)} title="Focus on ${esc(r.dimension)}"><span class="rank-label">${i+1}. ${esc(readableDimension(data.by,r.dimension))}</span><strong>${compact(r[data.metric])}<small>${percent(data.summary[data.metric]?r[data.metric]/data.summary[data.metric]:null)}</small></strong><svg viewBox="0 0 400 6" preserveAspectRatio="none" aria-hidden="true"><rect width="400" height="6" class="bar-track"/><rect width="${r[data.metric]/max*400}" height="6" class="bar-value"/></svg></button>`).join('')}</div>`;
}
function tokenMix(data){
  const s=data.summary,total=s.total_tokens;
  const rows=[['uncached_input_tokens','Uncached input'],['cached_input_tokens','Cached input'],['output_tokens','Output']];
  // Disjoint quantities only: cached input is removed from the uncached segment.
  const items=rows.map(([key,label])=>({dimension:label,value:s[key],other:true,color:{uncached_input_tokens:'token-uncached',cached_input_tokens:'token-cached',output_tokens:'token-output'}[key]}));
  return donut(items,total,'', 'value','Token composition')+`<div class="mix-actions">${rows.map(([key,label])=>`<button data-ana-metric="${key}">Explore ${label.toLowerCase()}</button>`).join('')}</div><p class="chart-footnote">Input = uncached + cached. Reasoning is included in output; cache writes are an input subset and are not added again.</p>`;
}
function modelColor(model){
  let hash=2166136261;for(const char of model)hash=Math.imul(hash^char.charCodeAt(0),16777619);
  return `hsl(${(hash>>>0)%360} 52% 43%)`;
}
function trendChart(data){
  const rows=data.timeline,max=Math.max(...rows.map(r=>r[data.metric]),1),w=900,h=190,slot=w/Math.max(rows.length,1);
  if(!rows.length)return '<p class="chart-empty">No recorded activity in this period.</p>';
  const models=trendMode==='model',stacked=data.metric==='total_tokens';
  const bars=rows.map((r,i)=>{
    let y=h;
    const segments=models?data.timeline_models.map((model,index)=>({value:model.values[i],label:model.model,modelIndex:index,color:modelColor(model.model)})):
      (stacked?[['cached_input_tokens','cached'],['uncached_input_tokens','uncached'],['output_tokens','output']]:[[data.metric,'uncached']]).map(([key,cls])=>({value:r[key],label:metricLabels[key],cls}));
    return `<g><rect role="button" tabindex="0" data-ana-period="${i}" aria-label="Focus on ${esc(r.start.slice(0,10))}: ${fmt(r[data.metric])} ${esc(metricLabels[data.metric])}" x="${i*slot}" y="0" width="${slot}" height="${h}" class="trend-hit"><title>${esc(when(r.start))} to ${esc(when(r.end))} UTC (end exclusive): ${fmt(r[data.metric])}; ${fmt(r.records)} records</title></rect>${segments.map(segment=>{
      if(!segment.value)return '';
      const height=segment.value/max*(h-18);y-=height;
      const label=`${segment.label}: ${fmt(segment.value)} ${metricLabels[data.metric]} · ${when(r.start)} to ${when(r.end)} UTC (end exclusive)`;
      return `<rect role="button" tabindex="0" data-ana-period="${i}" ${models?`data-trend-model="${segment.modelIndex}" fill="${segment.color}"`:`class="${segment.cls}"`} aria-label="Focus on ${esc(label)}" x="${i*slot+slot*.15}" y="${y}" width="${Math.max(slot*.7,1)}" height="${height}"><title>${esc(label)}</title></rect>`;
    }).join('')}</g>`;
  }).join('');
  const legend=models?`<div class="model-trend-legend" aria-label="Models in the timeline">${data.timeline_models.map(m=>`<button ${drillAttrs('model',m.model)} title="Explore ${esc(m.model)} across this period"><svg width="12" height="12" viewBox="0 0 12 12" aria-hidden="true"><rect width="12" height="12" rx="2" fill="${modelColor(m.model)}"/></svg><span>${esc(m.model)}</span><strong>${compact(m.total)}</strong></button>`).join('')}</div><p class="chart-footnote">Every model is included. Hover a segment for exact usage; click it to focus on that model and interval. Legend buttons focus on a model across the selected period.</p>`:
    stacked?'<div class="legend trend-legend"><span><i class="cached"></i>Cached input</span><span><i class="uncached"></i>Uncached input</span><span><i class="output"></i>Output</span></div>':'';
  return `<div class="trend-scale"><span>${compact(max)}</span><span>${esc(metricLabels[data.metric])} per ${data.interval_days===1?'UTC day':data.interval_days+'-day interval'} · ${models?'stacked by model':stacked?'token composition':'unsplit total'}</span></div><svg class="analytics-trend" viewBox="0 0 ${w} ${h}" role="group" aria-label="Usage over time ${models?'by model':'by token type'}">${bars}</svg><div class="chart-axis"><span>${esc(rows[0].start.slice(0,10))}</span><span>Click an interval to focus · zero means no indexed records</span><span>${esc(rows.at(-1).end.slice(0,10))}</span></div>${legend}`;
}
function activityHeatmap(data){
  const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],values=new Map(data.heatmap.map(r=>[r.weekday+':'+r.hour,r.value])),max=Math.max(...data.heatmap.map(r=>r.value),1);
  return `<div class="heatmap-wrap"><svg viewBox="0 0 800 216" role="group" aria-label="Usage by weekday and hour in UTC">${Array.from({length:24},(_,hour)=>`<text x="${60+hour*30}" y="15" class="heatmap-label">${String(hour).padStart(2,'0')}</text>`).join('')}${[1,2,3,4,5,6,0].map((day,i)=>`<text x="0" y="${43+i*26}" class="heatmap-label">${days[day]}</text>${Array.from({length:24},(_,hour)=>{const key=String(hour).padStart(2,'0'),value=values.get(day+':'+key)||0,level=value?Math.min(4,Math.max(1,Math.ceil(value/max*4))):0;return `<g role="button" tabindex="0" data-ana-hour="${key}" data-ana-weekday="${day}" aria-label="Focus on ${days[day]} ${key}:00 UTC: ${fmt(value)} ${esc(metricLabels[data.metric])}"><title>${days[day]} ${key}:00–${key}:59 UTC: ${fmt(value)} ${esc(metricLabels[data.metric])}</title><rect x="${53+hour*30}" y="${25+i*26}" width="26" height="22" rx="3" class="heat-${level}"/></g>`;}).join('')}`).join('')}</svg></div><p class="chart-footnote">${esc(metricLabels[data.metric])} across the selected period. Darker cells mean more usage. Click a cell to inspect those records.</p>`;
}
function sizeChart(data){
  const values=new Map(data.distribution.map(r=>[r.bucket,r])),max=Math.max(...data.distribution.map(r=>r.records),1);
  return data.summary.response_records?`<div class="size-bars">${sizeBins.map(([label],i)=>{const r=values.get(i)||{records:0,total_tokens:0};return `<button class="rank-row" data-ana-size="${i}" title="${fmt(r.total_tokens)} tokens across ${fmt(r.records)} responses"><span>${label} tokens</span><strong>${fmt(r.records)}<small>responses</small></strong><svg viewBox="0 0 400 6" preserveAspectRatio="none" aria-hidden="true"><rect width="400" height="6" class="bar-track"/><rect width="${r.records/max*400}" height="6" class="bar-value"/></svg></button>`;}).join('')}</div><p class="chart-footnote">Native responses only; ranges include their lower bound. Average ${fmt(Math.round(data.summary.mean_response_tokens))} · median ${fmt(data.summary.median_response_tokens)} · P95 ${fmt(data.summary.p95_response_tokens)} tokens. P95 uses the nearest rank; legacy deltas are excluded.</p>`:'<p class="chart-empty">Response-size statistics need native response records. Legacy cumulative deltas do not establish individual response sizes.</p>';
}
function analyticsView(data){
  analysisData=data;
  const s=data.summary,c=data.comparison,unit=data.metric==='records'?'records':'tokens';
  const change=!c?'Select a dated period to compare':c.change_percent==null?(c.records?'Previous selection has zero quantity':'No records in the previous period'):`${c.change_percent>0?'+':''}${fmt(Math.round(c.change_percent*10)/10)}% vs previous equal-length period`;
  const fields=[['input_tokens','Input'],['cached_input_tokens','Cached¹'],['uncached_input_tokens','Uncached'],['output_tokens','Output'],['reasoning_output_tokens','Reasoning¹'],['cache_write_input_tokens','Cache write¹'],['total_tokens','Total']];
  return header('Consumption analysis','Find what consumed your tokens, where it ran, and which records explain it.',`<button data-ana-action="records">Open matching records →</button>`)+filterBar(recordQuery(data))+
    `<div class="analysis-toolbar"><label>Break down by <select id="by">${Object.entries(dimensionLabels).filter(([k])=>!['weekday','hour'].includes(k)).map(([k,v])=>`<option value="${k}" ${filters.by===k?'selected':''}>${v}</option>`).join('')}</select></label><label>Measure <select id="analysis-metric">${Object.entries(metricLabels).map(([k,v])=>`<option value="${k}" ${data.metric===k?'selected':''}>${v}</option>`).join('')}</select></label>${analysisTrail.length?'<button data-ana-action="back">← Back one level</button>':''}<span class="muted">Charts and groups use this measure</span></div>
    <div class="analytics-kpis"><article><span>${esc(metricLabels[data.metric])}</span><strong>${compact(s[data.metric])}</strong><small>${fmt(s[data.metric])} exact · ${fmt(s.records)} metering records</small><small class="comparison">${esc(change)}</small></article><article><span>Scope in view</span><strong>${fmt(s.projects)} <em>projects</em></strong><small>${fmt(s.tasks)} distinct tasks · ${fmt(s.response_records)} native responses</small></article><article><span>Reported cache share</span><strong>${percent(s.cache_share)}</strong><small>${fmt(s.cached_input_tokens)} cached ÷ ${fmt(s.input_tokens)} input tokens</small></article><article><span>Tokens without a declared purpose</span><strong>${percent(s.total_tokens?s.undeclared_tokens/s.total_tokens:null)}</strong><small>${fmt(s.undeclared_tokens)} of ${fmt(s.total_tokens)} total tokens</small></article></div>
    <div class="section-heading"><h2>${fmt(s.total_tokens)} observed tokens in this selection</h2><span>Computed ${esc(when(data.as_of))} UTC</span></div>
    ${s.records?`<section class="analytics-panel trend-panel"><div class="panel-heading"><h2>When consumption happened</h2><label class="trend-split">Split by <select id="trend-split"><option value="model" ${trendMode==='model'?'selected':''}>Model</option><option value="tokens" ${trendMode==='tokens'?'selected':''}>Token type</option></select></label></div>${trendChart(data)}</section>
    <div class="analytics-grid"><section class="analytics-panel"><div class="panel-heading"><h2>Share by ${esc(dimensionLabels[data.by].toLowerCase())}</h2><span>${esc(metricLabels[data.metric])}</span></div>${donut(data.chart_groups,s[data.metric],data.by,data.metric,'Consumption share by '+dimensionLabels[data.by])}<p class="chart-footnote">Top five groups; the remainder is combined. Click a slice or label to drill down.</p></section><section class="analytics-panel"><div class="panel-heading"><h2>Largest consumers</h2><span>Top ${data.ranking.length} of ${fmt(data.total_groups)}</span></div>${rankingChart(data)}</section></div>
    <div class="analytics-grid"><section class="analytics-panel"><div class="panel-heading"><h2>What the tokens consist of</h2><span>All token types in selection</span></div>${tokenMix(data)}</section><section class="analytics-panel"><div class="panel-heading"><h2>Response sizes</h2><span>Native responses only</span></div>${sizeChart(data)}</section></div>
    <section class="analytics-panel"><div class="panel-heading"><h2>Activity by weekday and hour</h2><span>UTC · click a cell to focus</span></div>${activityHeatmap(data)}</section>`:empty('No consumption in this selection','Remove a drill-down filter, go back one level, or widen the period. No missing activity is inferred.')}`+
    `<div class="section-heading"><h2>Explore the groups</h2><span>${fmt(data.total_groups)} groups · all columns sortable</span></div>`+
    (data.groups.length?`<div class="table-wrap" tabindex="0" aria-label="Consumption breakdown"><table class="analysis-table"><thead><tr><th>${esc(dimensionLabels[data.by])}</th><th class="number">Records</th><th class="number">Tasks</th><th class="number">Share²</th>${fields.map(([k,t])=>`<th class="number">${t}</th>`).join('')}<th class="number">Cache share</th></tr></thead><tbody>${data.groups.map(g=>`<tr><td class="path"><button class="record-link" ${drillAttrs(data.by,g.dimension)} title="Explore ${esc(g.dimension)}">${esc(readableDimension(data.by,g.dimension))}</button></td><td class="number">${fmt(g.records)}</td><td class="number">${fmt(g.tasks)}</td><td class="number">${percent(g.share)}</td>${fields.map(([k])=>`<td class="number">${fmt(g[k])}</td>`).join('')}<td class="number">${percent(g.cache_share)}</td></tr>`).join('')}</tbody></table></div><div class="table-footer"><span>¹ Subsets are not added to Total. ² Share of selected ${esc(metricLabels[data.metric].toLowerCase())}.</span><div><span>${fmt(data.offset+1)}–${fmt(Math.min(data.offset+50,data.total_groups))} of ${fmt(data.total_groups)}</span><button data-ana-action="previous" ${data.offset===0?'disabled':''} aria-label="Previous groups">←</button><button data-ana-action="next" ${data.offset+50>=data.total_groups?'disabled':''} aria-label="Next groups">→</button></div></div>`:'')+
    (data.top_records.length?`<section class="analytics-panel largest-records"><div class="panel-heading"><h2>Largest individual metering records</h2><button data-ana-action="records">See all matching records</button></div><div class="record-cards">${data.top_records.map(e=>`<button class="large-record" data-event="${esc(e.id)}"><span><strong>${esc(projectName(e.effective_project))}</strong><small>${esc(e.model)} · ${esc(e.effective_actor||'Identity unknown')}</small><small>${esc(when(e.timestamp))} UTC · ${esc(e.granularity)}</small><small class="path">Task ${esc(e.thread_id||'unknown')}</small></span><span><strong>${fmt(e.total_tokens)}</strong><small>tokens · inspect evidence →</small></span></button>`).join('')}</div></section>`:'')+
    `<details class="analytics-method"><summary>Metric definitions, comparison period and coverage</summary><p>All charts use included records from the local accounting ledger, with the same period, search, evidence and drill-down filters. Provider cost buckets and quota percentages are separate evidence and are not added here. Source folders and devices identify recorded context or collectors, not verified remote execution locations.</p><p>${fmt(s.response_records)} native responses and ${fmt(s.records-s.response_records)} legacy deltas are in view. Token totals can combine these evidence types; response-size statistics use only native responses. Cache share uses reported cached input divided by all input; missing optional counts contribute zero. Cache writes and reasoning remain subsets, and no monetary savings are inferred.</p><p>Purpose coverage is weighted by total tokens. Missing purposes remain undeclared. Device and person identities may be unknown or locally declared. A zero chart bucket means no indexed consumption, not proof that no account activity occurred.</p>${c?`<p>Comparison uses the same non-date filters over ${esc(when(c.start))} to ${esc(when(c.end))} UTC (end exclusive), an equal elapsed interval immediately before the selection. Previous ${esc(metricLabels[data.metric].toLowerCase())}: ${fmt(c.value)} from ${fmt(c.records)} records. No percentage change is calculated from a zero baseline. Unequal source coverage can affect the comparison.</p>`:'<p>All recorded time has no preceding comparison period.</p>'}<p><a href="#coverage">Review source availability and collection notices</a> · <a href="/api/export?${recordQuery(data)}">Export the matching evidence rows</a></p></details>`;
}
async function analysisDrill(by,value){
  analysisRemember();filters.facets={...(filters.facets||{}),[by]:value};filters.offset=0;
  const next={project:'model',model:'task',task:'day',person:'project',purpose:'project',device:'project',directory:'model',branch:'task',application:'model',evidence:'project'};
  filters.by=next[by]||'task';sorts.analysis=[analysisMetric,'desc'];await load();
}
document.addEventListener('click',async event=>{
  const target=event.target.closest('[data-ana-drill],[data-ana-action],[data-ana-remove],[data-ana-metric],[data-ana-period],[data-ana-hour],[data-ana-size]');if(!target)return;
  try{
    if(target.hasAttribute('data-ana-drill'))return await analysisDrill(target.dataset.anaDrill,target.dataset.anaValue);
    if(target.dataset.anaMetric){analysisMetric=target.dataset.anaMetric;sorts.analysis=[analysisMetric,'desc'];filters.offset=0;return await load();}
    if(target.hasAttribute('data-ana-period')){analysisRemember();const row=analysisData.timeline[Number(target.dataset.anaPeriod)];filters.drillFrom=row.start;filters.drillTo=row.end;if(target.hasAttribute('data-trend-model')){const model=analysisData.timeline_models[Number(target.dataset.trendModel)];filters.facets={...(filters.facets||{}),model:model.model};filters.by='task';}filters.offset=0;return await load();}
    if(target.hasAttribute('data-ana-hour')){analysisRemember();filters.facets={...(filters.facets||{}),weekday:target.dataset.anaWeekday,hour:target.dataset.anaHour};filters.by='task';filters.offset=0;return await load();}
    if(target.hasAttribute('data-ana-size')){analysisRemember();const [,min,max]=sizeBins[Number(target.dataset.anaSize)];if(filters.tokens_min==null)filters.sizePreviousGranularity=filters.granularity;filters.tokens_min=min;filters.tokens_max=max;filters.granularity='response';filters.offset=0;return await load();}
    if(target.dataset.anaRemove){const key=target.dataset.anaRemove;if(key==='size'){filters.tokens_min=null;filters.tokens_max=null;filters.granularity=filters.sizePreviousGranularity??filters.granularity;delete filters.sizePreviousGranularity;}else if(key==='period'){delete filters.drillFrom;delete filters.drillTo;}else delete filters.facets[key];filters.offset=0;return await load();}
    const action=target.dataset.anaAction;
    if(action==='back'){const previous=analysisTrail.pop();if(previous){filters=previous.filters;analysisMetric=previous.metric;sorts.analysis=[analysisMetric,'desc'];}}
    if(action==='clear'){filters.facets={};if(filters.tokens_min!=null)filters.granularity=filters.sizePreviousGranularity??filters.granularity;delete filters.sizePreviousGranularity;filters.tokens_min=null;filters.tokens_max=null;delete filters.drillFrom;delete filters.drillTo;filters.offset=0;analysisTrail=[];}
    if(action==='previous')filters.offset=Math.max(0,filters.offset-50);
    if(action==='next')filters.offset+=50;
    if(action==='records'){filters.offset=0;filters.drillTo=analysisData.period.end;sorts.ledger=['total_tokens','desc'];location.hash='ledger';}
    await load();
  }catch(error){toast(error.message);}
});
document.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.matches('svg [role="button"]')){event.preventDefault();event.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
document.addEventListener('change',event=>{if(event.target.id==='trend-split'){trendMode=event.target.value;load();}if(['range','from','to'].includes(event.target.id)){delete filters.drillFrom;delete filters.drillTo;}if(event.target.id==='granularity'){filters.tokens_min=null;filters.tokens_max=null;delete filters.sizePreviousGranularity;}if(event.target.id==='analysis-metric'){analysisMetric=event.target.value;sorts.analysis=[analysisMetric,'desc'];filters.offset=0;load();}});
